version: "3.9"
services:
  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - se
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  web-service:
    image: ghcr.io/xii1/se-project:$WEB_SERVICE_TAG
    ports:
      - "8080"
    restart: always
    networks:
      - se
    depends_on:
      - mysql-db

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - se
    depends_on:
      - web-service

networks:
  se: